# ########################################################## #
#                ____           _____     _                  #
#               |  _ \ _____  _|_   _|_ _| |__               #
#               | |_) / _ \ \/ / | |/ _` | '_ \              #  
#               |  __/  __/>  <  | | (_| | |_) |             #
#               |_|   \___/_/\_\ |_|\__,_|_.__/              #
#                                                            #
# ########################################################## #

# This is the PexTab main configuration file.                #
# Colors. If you want to set the color up to red just        #
# replace default variable with 'c' or '4'.                  #
# Braces. You can enable it or disable by simply typing      #
# 'true' or 'false'.                                         #
# Example: Braces: true will make it looks like '[Group]'.   #

# ########################################################## #

Color: b
Braces: true
BracesColor: 8
NicknameColor: 8

